[package]
name = "pumpmine-miner"
version = "2.1.0"
edition = "2021"
authors = ["Ice"]
license = "MIT"
description = "The GPU accelerated keccak256 miner for Pumpmine"

[[bin]]
name = "pumpmine-miner"
path = "src/main.rs"

[dependencies]
ash       = "0.37"
bytemuck  = { version = "1", features = ["derive"] }
anyhow    = "1"
hex       = "0.4"
tiny-keccak = { version = "2", features = ["keccak"] }
env_logger = "0.11"
log        = "0.4"
alloy = { version = "1.7.3", features = ["full"] }
tokio = { version = "1.50.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.0"
clap = { version = "4.6.0", features = ["derive"] }

[build-dependencies]
shaderc = "0.8"

[profile.release]
opt-level = 3
